[build]
  command = "cp netlify-package.json package.json && npm install --legacy-peer-deps && npx vite build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5000
  publish = "dist"
